import { Dimensions, StyleSheet } from "react-native";
import { colors,fontSize } from "../globalStyles";

const {width}=Dimensions.get('screen')

export default StyleSheet.create({
  view:{
    flex:1,
    alignItems:'center',
    backgroundColor:colors.background,
  },
  titulo:{
    fontWeight:'700',
    color:colors.titulo,
    fontSize:fontSize.medium,
  },
  containerDadosGeral:{
    height:300,
    width:"100%",
    paddingTop:20,
    flexDirection:'row',
    paddingHorizontal:'5%',
  },
  containerImg:{
    width:120,
    height:'100%',
  },
  img:{
    width:120,
    height:120,
    borderRadius:120
  },
  containerContacts:{
    alignItems:'center'
  },
  containerContact:{
    flexDirection:'row',
    marginTop:10
  },
  txtContato:{
    marginLeft:5,
    color:colors.texto,
    fontSize:fontSize.small,
    textAlignVertical:'center'
  },
  subTitle:{
    marginTop:10,
    fontWeight:'700',
    color:colors.titulo,
    fontSize:fontSize.normal,
  },
  containerDados:{
    flex:1,
    height:250,
    marginLeft:10,
    alignItems:'center',
    
  },
  containerLista:{
    marginTop:20,
    borderRadius:20,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:colors.backgroundBlocos
  },
  containerDadosLista:{
    flexDirection:'row',
  },
  personalDatas:{
    width:'50%',
    height:'100%',
    alignItems:'center'
  },
  containerDefault:{
    marginVertical:10,
    alignItems:'center',
    flexDirection:'row',
  },
  txt:{
    marginLeft:5,
    color:colors.texto
  },
  containerListaSkills:{
    justifyContent:'space-around',
    flexDirection:'row',
    flexWrap:'wrap',
  },
//Segunda parte da Tela
  linha:{
    width,
    height:2,
    backgroundColor:colors.divisao
  },
  containerExp:{
    width,
    marginTop:15,
    paddingBottom:30,
    alignItems:'center',
  },
  tituloExp:{
    marginVertical:0,
    fontWeight:'700',
    color:colors.titulo,
    fontSize:fontSize.medium,
  },
})