import { StyleSheet } from "react-native";

export default StyleSheet.create({
  imgContainer:{
    flex:1,
    width:'100%',
    height:'100%',
    alignItems:'center',
    overflow:'hidden',
    borderRadius:8,
  },
  logoContainer:{
    alignItems:'center',
    justifyContent:'center',
    width:'100%',
    height:200
  },
  imgLogo:{
    flex:1,
    width:'65%',
    resizeMode:'contain'
  },
  divider:{
    alignSelf:'center',
    height:1,
    width:'80%',
    backgroundColor:'#01A6B3',
    marginVertical:10
  },
  containerDetails:{
    alignItems:'center'
  },
  carBrand:{
    color:'#fff',
    fontWeight:'400',
    fontSize:18,
    fontStyle:'italic'
  },
  carModel:{
    color:'#fff',
    fontSize:20,
    fontWeight:'bold',
    textAlign:'center'
  },
  img:{
    flex:1,
    marginBottom:10,
    width:'100%',
    height:'80%',
  },
  containerButton:{
    backgroundColor:"#01A6B3",
    padding:10,
    width:'80%',
    alignItems:'center',
    justifyContent:'center',
    alignSelf:'center',
    borderRadius:8,
    marginBottom:10
  },
  button:{
    flexDirection:'row',
    justifyContent:'center',
    alignItems:"center"
  },
  txtButton:{
    color:'#fff',
    fontSize:18,
    fontWeight:'bold',
    fontStyle:'italic',
    marginLeft:5
  },
  containerPrice:{
    width:"100%",
    flexDirection:'row',
    justifyContent:'space-around',
    paddingBottom:10,
    alignItems:"center",
  },
  price:{
    color:'#fff',
    fontSize:22

  }

})